package input

import "github.com/hajimehoshi/ebiten/v2"

var KeyNames = map[ebiten.Key]string{
	ebiten.KeyA:       "A",
	ebiten.KeyB:       "B",
	ebiten.KeyC:       "C",
	ebiten.KeyD:       "D",
	ebiten.KeyE:       "E",
	ebiten.KeyF:       "F",
	ebiten.KeyG:       "G",
	ebiten.KeyH:       "H",
	ebiten.KeyI:       "I",
	ebiten.KeyJ:       "J",
	ebiten.KeyK:       "K",
	ebiten.KeyL:       "L",
	ebiten.KeyM:       "M",
	ebiten.KeyN:       "N",
	ebiten.KeyO:       "O",
	ebiten.KeyP:       "P",
	ebiten.KeyQ:       "Q",
	ebiten.KeyR:       "R",
	ebiten.KeyS:       "S",
	ebiten.KeyT:       "T",
	ebiten.KeyU:       "U",
	ebiten.KeyV:       "V",
	ebiten.KeyW:       "W",
	ebiten.KeyX:       "X",
	ebiten.KeyY:       "Y",
	ebiten.KeyZ:       "Z",
	ebiten.KeyLeft:    "Left",
	ebiten.KeyRight:   "Right",
	ebiten.KeyUp:      "Up",
	ebiten.KeyDown:    "Down",
	ebiten.KeySpace:   "Space",
	ebiten.KeyEnter:   "Enter",
	ebiten.KeyShift:   "Shift",
	ebiten.KeyControl: "Ctrl",
	ebiten.KeyEscape:  "Esc",
}

func KeyName(k ebiten.Key) string {
	if name, ok := KeyNames[k]; ok {
		return name
	}
	return k.String()
}
